# Generated by Django 5.1.7 on 2025-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa_titulo', models.CharField(max_length=100, unique=True)),
                ('tarefa_descricao', models.CharField(default='', max_length=250)),
                ('tarefa_prazo', models.DateField(blank=True, null=True)),
                ('tarefa_dataConclusao', models.DateField(blank=True, null=True)),
                ('tarefa_situacao', models.CharField(choices=[('Nova', 'Nova'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Nova', max_length=20)),
            ],
        ),
    ]
