# Generated by Django 5.1.7 on 2025-03-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('tarefa_titulo', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('tarefa_descricao', models.CharField(default='', max_length=250)),
                ('tarefa_prazo', models.DateField(default='')),
                ('tarefa_dataConclusao', models.DateField(default='')),
                ('tarefa_situacao', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='', max_length=3)),
            ],
        ),
    ]
