# Generated by Django 5.1.7 on 2025-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tarefa_dataConclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tarefa_prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tarefa_situacao',
            field=models.CharField(choices=[('Nova', 'Nova'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='', max_length=20),
        ),
    ]
